export const Airport = [
  {name:'اراک', latin:'AJK'},
  {name:'ارومیه', latin:'OMH'},
  {name:'اردبیل', latin:'ADU'},
  {name:'اصفهان', latin:'IFN'},
  {name:'اهواز', latin:'AWZ'},
  {name:'ایلام', latin:'IIL'},
  {name:'بندرعباس', latin:'BND'},
  {name:'بوشهر', latin:'BUZ'},
  {name:'بیرجند', latin:'XBJ'},
  {name:'تبریز', latin:'TBZ'},
  {name:'تهران', latin:'THR'},
  {name:'خرم آباد', latin:'KHD'},
  {name:'رشت', latin:'RAS'},
  {name:'زنجان', latin:'JWN'},
  {name:'زاهدان', latin:'ZAH'},
  {name:'ساری', latin:'SRY'},
  {name:'سنندج', latin:'SDG'},
  {name:'شهرکرد', latin:'CQD'},
  {name:'شیراز', latin:'SYZ'},
  {name:'عسلویه', latin:'PGU'},
  {name:'قشم', latin:'GSM'},
  {name:'کرج', latin:'PYK'},
  {name:'کرمان', latin:'KER'},
  {name:'کرمانشاه', latin:'KSH'},
  {name:'کیش', latin:'KIH'},
  {name:'گرگان', latin:'GBT'},
  {name:'مشهد', latin:'MHD'},
  {name:'همدان', latin:'HDM'},
  {name:'یاسوج', latin:'YES'},
  {name:'یزد', latin:'AZD'},
]